---
format:
  # Delete the format that you don't want
  # Presentation
  aagi-revealjs: default
  aagi-pptx: default
  # Report
  aagi-pdfreport: default # full length pdf report
  aagi-pdfshortreport: default # short pdf report (typically one page)
  aagi-docxreport: default # full length word docx report
  aagi-docxshortreport: default # short word docx report (typically one page)
execute:
  echo: false
# Delete these if you're using the template for presentation
knitr:
  opts_chunk:
    fig.path: figures/
params:
  # All the params can be changed to align to your organisation and collaborator.
  # These can be changed here or in the terminal using the following command with
  # each -P represents a parameter:
  #             quarto render ... -P $params$:... -P $params2$:///
  uni: CU
  pri_bio: Your.Name
  project_num: AAA--BBB
  partner: collab_partner
  partner_email: collab_partner@email.com.au
  # REQUIRED: provide the AAGI contact email
  aagi_email: "contact@institution.edu"
date: last-modified
date-format: long
bibliography: your_references.bib # Replace with your .bib file
csl: ../_extensions/aagi/assets/biometrics.csl
---

```{r}
#| include: false
#| label: setup

source("_scripts/setup_reports.R", local = TRUE)
```

---
title: "Analytics for the Australian Grains Industry - `r uni_name` (AAGI-`r params$uni`)  \n Technical Report Series: 123"
# To force line spacing put two spaces before \n instead of one
subtitle: "Descriptive title for report  \n Report for `r params$project_num`"
author:
  - "Prepared for: `r params$partner` (`r params$partner_email`)"
  - "Prepared by: `r params$pri_bio`, Author 2"
email: "`r aagi_email`"
---

# To compile a presentation, please see:

-   Revealjs: <https://quarto.org/docs/presentations/revealjs/>

-   PowerPoint: <https://quarto.org/docs/presentations/powerpoint.html>

# Executive summary

What was provided by AAGI and the main results?

-   Citation example (@sparks2018nasapower), another example @butler2017asreml and @brien2020asremlplus.

# Introduction

-   Goals of the research project.

-   Background, context and rationale behind the research.

# Experimental/Trial Design

-   Trial design type and layout.

-   Treatments, number of replicates.

-   Specific considerations for small plots, glasshouse, genetics, breeding trials, OFE projects, or bioinformatics.

# Exploratory Data Analysis and Data Visualisation

-   Interpretation of plots and data.

-   Rationale behind specific methods used.

# Methods

-   Detailed description of the procedures and methodologies used.

-   Include versions/commits on developed pipelines, scripts, and input/output details if applicable.

# Analysis (if separate from Methods)

Approach taken for data analysis.

# Results and Discussion

Findings and their implications.

# Metadata and Datasets (Optional)

-   md5sums for input data and outputs (if applicable).

-   Git commit numbers and tags.

-   Location of outputs (FAIR Data).

-   DOI for AAGI outputs.

# Map (Location, Optional)

Include if relevant to the project.

# Conclusion or Discussion

-   Summary of the main findings.
-   Implications for the industry (for example).

# Acknowledgements

-   Funding sources.
-   Collaborators.

# References

Cited works and literature.

::: {#refs}
:::

# Appendix (Optional)

Additional supporting information.
