project:
  type: website
  resources:
   - assets/*

website:
  title: "AAGIQuarto"
  reader-mode: true
  repo-url: https://github.com/AAGI-AUS/AAGIQuarto
  repo-actions: [edit, issue]
  margin-header: |
    ![](/aagi-logo.svg)
  body-footer: |
    ![](/Partners.svg)
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/AAGI-AUS/AAGIQuarto
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Extra"
        contents:
        - release-notes.qmd

format: 
  html:
    toc: true
    theme: aagi.scss
