---
title: "Release Notes"
date: last-modified
engine: markdown
format:
  html:
    toc: true
---

# 2.0.0 2026-06-17

## Breaking changes

* Example template defaults to long report PDF format, no longer combining all possible formats.

## Major changes 

* Improved font handling including supplying woff2 files of Firacode and autodetection of Proxima Nova across all OSes for PDF output.
* Better example file rendering via Makefile.

## Bug fixes 

* Fix bug where example template would not render properly when using `quarto use template AAGI-AUS/AAGIQuarto` as reported by [\@William-Pincombe](https://github.com/William-Pincombe).
* Correct colours and list formatting in CSS for HTML and Revealjs outputs.
* Fix download link for downloading a zip file of the demonstration templates for users to modify and use.

# 1.0.1 2026-05-04

## Minor changes

* Update the strategic partner logo block.

## Bug fixes

* Fix links in README to example output files (these were working from the Quarto website but not from the README).

# 1.0.0 2026-04-07

## Major changes

* Add long and short HTML format reports.

## Minor changes

* Fix Adelaide University in parameters of "template.qmd".

## Bug fixes

* Ensure that "AU" and "Adelaide University" are used in the documents.
* Fix bug in "_extension.yml" where the asset for the partner logo block was incorrectly referred to.
* Lint files.

# 0.1.5 2026-03-26

## Minor changes

* Update SP logo block to use new AU logo and new order.
* Polish extension contents, delete extra files, lint and format files.

# 0.1.4 2025-07-29

## Minor changes

* More polishing missed in last round, _e.g._, duplicated labels, etc.

# 0.1.3 2025-07-29

## Minor changes

* Set language in Word document templates to en-AU.
* Enhance installation instructions.
* Add header and footer to full length reports.
* Install AAGI R packages using R-Universe methods.

## Bug fixes

* Ensure `\usepackage{hyperref}` is called.
* Spelling corrections.

# 0.1.2 2024-12-11

## Minor changes

* Add example using {flextable} in AAGI Short Report PDF format document.

## Bug fixes

* Fix bug in AAGI Short Report PDF format wherein using {flextable} caused the PDF to not compile properly (at all).

# 0.1.1 2024-10-28

## Minor changes

* Add example outputs for reports using AAGI themes for graphs and tables.
* Add starter pack instructions for easily creating an AAGI file rather than setting up your own YAML.
* Fix links in README.

# 0.1.0 2024-09-26

## Major changes

* First stable release with support for MS Word, PowerPoint, revealjs and long and short report PDF outputs with LaTeX.
