---
format:
  aagi-pptx:
    fig-path: figures/pptx/
execute:
  echo: false
  message: false

title: "AAGI PPTX Presentation"
author: "Adam Sparks"
date: last-modified
date-format: long
---

```{r}
#| label: setup
#| include: false
#| message: false

source("_scripts/setup_presentations.R", local = TRUE)

try(ggplot2::theme_set(AAGIThemes::theme_aagi()), silent = TRUE)
try(
  flextable::set_flextable_defaults(theme_fun = AAGIThemes::theme_ft_aagi),
  silent = TRUE
)
```

## An AAGI pptx Theme for Quarto

This Quarto extension allows you to create slides using an AAGI-styled theme.

## Bullet point

- Point 1
- Point 2

## Tables

For tables, we suggest using {AAGIThemes} with `theme_ft_aagi`.

## Example

```{r}
#| label: tab-aagi
#| message: false

library(flextable)
library(dplyr)

flex_tab <- flextable(
  head(airquality) |>
    mutate(`Month Name` = "May")
) |
  theme_ft_aagi() |
  autofit()

flex_tab
```

## Basic Figures

```{r}
#| label: graphics-figure
#| message: false

plot_aagi(pressure)
```

## Figures with {ggplot2}

```{r}
#| label: ggplot2-figure
#| message: false

library(ggplot2)

facet <- gapminder |>
  dplyr::filter(continent != "Americas") |>
  dplyr::group_by(continent, year) |>
  dplyr::summarise(pop = sum(as.numeric(pop)), .groups = "drop")

col_values <- c(
  AAGIPalettes::colour_as_hex("AAGI Teal"),
  AAGIPalettes::colour_as_hex("AAGI Green"),
  AAGIPalettes::colour_as_hex("AAGI Yellow"),
  AAGIPalettes::colour_as_hex("AAGI Blue")
)

ggplot() +
  geom_area(data = facet, aes(x = year, y = pop, fill = continent)) +
  scale_fill_manual(values = col_values) +
  facet_wrap(~continent, ncol = 5) +
  scale_y_continuous(
    breaks = c(0, 2000000000, 4000000000),
    labels = c(0, "2bn", "4bn")
  ) +
  theme_aagi() +
  geom_hline(yintercept = 0, linewidth = 1, colour = "#474747") +
  theme(legend.position = "none", axis.text.x = element_blank()) +
  labs(
    title = "Asia's rapid growth",
    subtitle = "Population growth by continent, 1952–2007"
  )
```

## Slides With Columns

::::: columns
::: {.column width="50%"}
This is a column on the left.
:::

::: {.column width="50%"}
This is a column on the right.
:::
:::::

# Thank You
