on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch: {}

name: demo-website

jobs:
  demo-page:
    runs-on: ubuntu-latest

    # Restrict concurrent publishes per ref
    concurrency:
      group: quarto-publish-${{ github.ref }}

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # recommended for versioned sites / changelogs

      # Quarto's knitr engine needs R available
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pak
        run: install.packages('pak', repos = 'https://r-lib.github.io/p/pak/dev/')
        shell: Rscript {0}

      - name: Install R (and system) dependencies with pak
        run: |
          pak::pkg_install(c(
            "knitr",
            "rmarkdown",
            "downlit",
            "xml2",
            "ggplot2",
            "sysfonts",
            "flextable"   # add other pkgs you use!
          ))
        shell: Rscript {0}

      # Install ms-corefonts for Arial (Proxima Nova not available on runners)
      - name: Install ms-corefonts
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer libfontconfig1-dev libcairo2-dev libcurl4-openssl-dev

      - name: Update font cache
        run: sudo fc-cache -fv

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
